### ISSUE TITLE
Development Chat

### ISSUE THREAD

**Issue by SidIcarus** [rohilthopu/pad-calendar#1]
Yo,

I was thinking about doing this as well but you've gotten a head start. I was thinking of setting up a slack / gitter / discord / etc to be able to chat about it if other people became interested in it as well as for tool integrations. Do you have any preference for chat tool?

**Comment by rohilthopu** [comment]
Hey!

If you wanna set up a chat for it, go ahead. I'm cool with whatever service. I think slack is probably the most accessible, but I have no idea these days lol.

Nice timing though, I was about to post on reddit sometime soon to see if anyone had any Python/Django, Swift, or Frontend experience haha. 

-Rohil

**Comment by rohilthopu** [comment]
Hello again,

I went ahead and made a Slack group since I had some time. If you'd like to join, I added an invite to the Readme.
